run: proj_2.cpp ../sources/mesh.cpp ../headers/mesh.h ../sources/conv2D.cpp ../headers/conv2D.h
	g++ proj_2.cpp ../sources/mesh.cpp ../sources/conv2D.cpp -o run
clean:
	rm -f *~
resetf:
	rm -f *~ pdata bdata run
	rm -rf results
	rm -f reg*


